#ifndef GUARD_MIRAGE_LOCATIONS_H
#define GUARD_MIRAGE_LOCATIONS_H

#define MIRAGE_LOCATION_NONE            0
#define MIRAGE_LOCATION_ROUTE_106       1
#define MIRAGE_LOCATION_ROUTE_114       2
#define MIRAGE_LOCATION_LILYCOVE_CITY   3
#define MIRAGE_LOCATION_ROUTE_125       4
#define MIRAGE_LOCATION_ROUTE_130       5
#define MIRAGE_LOCATION_ROUTE_123       6

#define NUM_MIRAGE_LOCATIONS 6

#endif // MIRAGE_LOCATIONS