#ifndef GUARD_MIRAGE_LOCATIONS_H
#define GUARD_MIRAGE_LOCATIONS_H

#define MIRAGE_LOCATION_NONE            0
#define MIRAGE_LOCATION_ROUTE_106       1
#define MIRAGE_LOCATION_ROUTE_114       2
#define MIRAGE_LOCATION_ROUTE_125       3
#define MIRAGE_LOCATION_ROUTE_130       4

#define NUM_MIRAGE_LOCATIONS 4

#endif // MIRAGE_LOCATIONS