#ifndef GUARD_MIRAGE_LOCATIONS_H
#define GUARD_MIRAGE_LOCATIONS_H

#define MIRAGE_LOCATION_NONE            0
#define MIRAGE_LOCATION_ROUTE_125       1
#define MIRAGE_LOCATION_ROUTE_130       2

#define NUM_MIRAGE_LOCATIONS 2

#endif // MIRAGE_LOCATIONS